buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://files.minecraftforge.net/maven' }
    }
    dependencies {
        classpath 'com.github.Chocohead:ForgeGradle:moderniser-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.tweaker-client'
apply plugin: 'java'

group = 'com.memorysweep'
version = '1.0.0'
archivesBaseName = 'memorysweep'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url 'https://www.jitpack.io' }
}

dependencies {
    implementation 'com.github.chocohead:rift:2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff'
}

minecraft {
    version = '1.13.2'
    mappings = 'snapshot_20181130'
    runDir = 'run'
    tweakClass = 'org.dimdev.riftloader.launch.RiftLoaderClientTweaker'
}

processResources {
    filesMatching('riftmod.json') {
        expand 'version': project.version
    }
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.archivesBaseName}" }
    }
}
